// File generated by FlutterFire CLI or fallback configuration.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static const String _defaultApiKey =
      'AIzaSyAn-JExkq3gb_20pTqk8wIMl_TNBMjjS3Q';
  static const String _defaultAppIdWeb =
      '1:124464777845:web:a4bbdf5cfbc636f596063c';
  static const String _defaultAppIdAndroid =
      '1:124464777845:android:4862cf1c9aa227dd96063c';
  static const String _defaultProjectId = 'gradtrack-db12d';
  static const String _defaultMessagingSenderId = '124464777845';
  static const String _defaultAuthDomain =
      'gradtrack-db12d.firebaseapp.com';
  static const String _defaultStorageBucket =
      'gradtrack-db12d.firebasestorage.app';
  static const String _defaultMeasurementId = 'G-SCNXKV613D';

  static String _env(String key, String fallback) {
    final val = dotenv.env[key];
    if (val != null && val.isNotEmpty && !val.contains('placeholder')) {
      return val;
    }
    return fallback;
  }

  static bool get isConfigured => true;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: _env('FIREBASE_API_KEY', _defaultApiKey),
        appId: _env('FIREBASE_APP_ID', _defaultAppIdWeb),
        messagingSenderId:
            _env('FIREBASE_MESSAGING_SENDER_ID', _defaultMessagingSenderId),
        projectId: _env('FIREBASE_PROJECT_ID', _defaultProjectId),
        authDomain: _env('FIREBASE_AUTH_DOMAIN', _defaultAuthDomain),
        storageBucket:
            _env('FIREBASE_STORAGE_BUCKET', _defaultStorageBucket),
        measurementId:
            _env('FIREBASE_MEASUREMENT_ID', _defaultMeasurementId),
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: _env('FIREBASE_API_KEY', _defaultApiKey),
        appId: _env('FIREBASE_ANDROID_APP_ID', _defaultAppIdAndroid),
        messagingSenderId:
            _env('FIREBASE_MESSAGING_SENDER_ID', _defaultMessagingSenderId),
        projectId: _env('FIREBASE_PROJECT_ID', _defaultProjectId),
        storageBucket:
            _env('FIREBASE_STORAGE_BUCKET', _defaultStorageBucket),
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: _env('FIREBASE_API_KEY', _defaultApiKey),
        appId: _env('FIREBASE_APP_ID', _defaultAppIdWeb),
        messagingSenderId:
            _env('FIREBASE_MESSAGING_SENDER_ID', _defaultMessagingSenderId),
        projectId: _env('FIREBASE_PROJECT_ID', _defaultProjectId),
        storageBucket:
            _env('FIREBASE_STORAGE_BUCKET', _defaultStorageBucket),
        iosBundleId: 'ph.edu.bisu.gradtrack',
      );

  static FirebaseOptions get macos => ios;

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: _env('FIREBASE_API_KEY', _defaultApiKey),
        appId: _env('FIREBASE_APP_ID', _defaultAppIdWeb),
        messagingSenderId:
            _env('FIREBASE_MESSAGING_SENDER_ID', _defaultMessagingSenderId),
        projectId: _env('FIREBASE_PROJECT_ID', _defaultProjectId),
        storageBucket:
            _env('FIREBASE_STORAGE_BUCKET', _defaultStorageBucket),
      );
}
