// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn-JExkq3gb_20pTqk8wIMl_TNBMjjS3Q',
    appId: '1:124464777845:web:a4bbdf5cfbc636f596063c',
    messagingSenderId: '124464777845',
    projectId: 'gradtrack-db12d',
    authDomain: 'gradtrack-db12d.firebaseapp.com',
    storageBucket: 'gradtrack-db12d.firebasestorage.app',
    measurementId: 'G-SCNXKV613D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMwPTRDzEH7Cow_fwccqcHGpKRq94vJ00',
    appId: '1:124464777845:android:4862cf1c9aa227dd96063c',
    messagingSenderId: '124464777845',
    projectId: 'gradtrack-db12d',
    storageBucket: 'gradtrack-db12d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn-JExkq3gb_20pTqk8wIMl_TNBMjjS3Q',
    appId: '1:124464777845:web:40324ffd566bb6bf96063c',
    messagingSenderId: '124464777845',
    projectId: 'gradtrack-db12d',
    authDomain: 'gradtrack-db12d.firebaseapp.com',
    storageBucket: 'gradtrack-db12d.firebasestorage.app',
    measurementId: 'G-GJB3DZRDMQ',
  );
}
